export const menuItems = [
  {
    id: "beranda",
    title: "Beranda",
    icon: "Home",
    role: ["admin", "ptgs-sensus", "admin-data-center", "pengurus"],
    link: "/",
  },
  {
    id: "auth",
    title: "Manajemen",
    icon: "KeyRound",
    role: ["admin"],
    submenu: [
      {
        id: "auth-users",
        title: "Users",
        icon: "UserCog",
        role: ["admin"],
        link: "/auth/users",
      },
      {
        id: "auth-roles",
        title: "Roles",
        icon: "ShieldHalf",
        role: ["admin"],
        link: "/auth/roles",
      },
      {
        id: "auth-logs",
        title: "logs",
        icon: "FileText",
        role: ["admin"],
        link: "/auth/logs",
      },
    ],
  },
  {
    id: "digitaldata",
    title: "Digital Data",
    icon: "MonitorCog",
    role: ["admin", "ptgs-sensus", "admin-data-center", "pengurus"],
    submenu: [
      {
        id: "digitaldata-sensus",
        title: "Sensus",
        icon: "Users",
        role: ["admin", "ptgs-sensus", "admin-data-center", "pengurus"],
        link: "/sensus",
      },
      {
        id: "digitaldata-cai",
        title: "CAI",
        icon: "Droplet",
        role: ["admin", "ptgs-sensus"],
        link: "/cai",
      },
      {
        id: "digitaldata-laporanbulanan",
        title: "Laporan Bulanan",
        icon: "Repeat2",
        role: ["admin", "ptgs-sensus", "admin-data-center", "pengurus"],
        submenu: [
          {
            id: "digitaldata-laporanbulanan-report",
            title: "Report",
            icon: "File",
            role: ["admin", "ptgs-sensus", "admin-data-center", "pengurus"],
            link: "/laporan-bulanan",
          },
          {
            id: "digitaldata-laporanbulanan-check",
            title: "Laporan Bulanan Check",
            icon: "CheckCheckIcon",
            role: ["admin", "admin-data-center"],
            link: "/laporan-bulanan/check",
          },
          {
            id: "digitaldata-laporanbulanan-monitoring-users",
            title: "Monitoring User",
            icon: "Users",
            role: ["admin", "admin-data-center"],
            link: "/laporan-bulanan/monitoring-users",
          },
          {
            id: "digitaldata-laporanbulanan-warnings",
            title: "Warnings",
            icon: "AlertTriangle",
            role: ["admin", "admin-data-center"],
            link: "/laporan-bulanan/warnings",
          },
        ],
      },
    ],
  },
  {
    id: "master-data",
    title: "Master Data",
    icon: "Container",
    role: ["admin", "ptgs-sensus", "admin-data-center", "pengurus"],
    submenu: [
      {
        id: "masterdata-pindahsambung",
        title: "Pindah Sambung",
        icon: "Route",
        role: ["admin", "ptgs-sensus", "admin-data-center", "pengurus"],
        link: "/master-data/pindah-sambung",
      },
      {
        id: "masterdata-tempatsambung",
        title: "Tempat Sambung",
        icon: "Server",
        role: ["admin"],
        submenu: [
          {
            id: "masterdata-tempatsambung-daerah",
            title: "Daerah",
            icon: "Database",
            role: ["admin"],
            link: "/master-data/tempat-sambung/daerah",
          },
          {
            id: "masterdata-tempatsambung-desa",
            title: "Desa",
            icon: "Database",
            role: ["admin"],
            link: "/master-data/tempat-sambung/desa",
          },
          {
            id: "masterdata-tempatsambung-kelompok",
            title: "Kelompok",
            icon: "Database",
            role: ["admin"],
            link: "/master-data/tempat-sambung/kelompok",
          },
        ],
      },
      {
        id: "masterdata-pekerjaan",
        title: "Pekerjaan",
        icon: "BicepsFlexed",
        role: ["admin"],
        link: "/master-data/pekerjaan",
      },
    ],
  },
  {
    id: "presensi",
    title: "Presensi",
    icon: "ScanQrCode",
    role: ["admin", "ptgs-sensus", "admin-data-center", "pengurus"],
    link: "/presensi",
  },
  {
    id: "pengaduan",
    title: "Pengaduan",
    icon: "MailWarning",
    role: ["admin", "admin-data-center"],
    link: "/pengaduan",
  },
];
